### ISSUE TITLE
F16

### ISSUE THREAD

**Issue by forgi86** [GerbenBeintema/nonlinear_benchmarks#1]
Hi Gerben,

I was trying to load the F16 dataset:

`f16_dataset = nonlinear_benchmarks.not_splitted_benchmarks.F16(force_download=True)`

but it throws an error. I can go around it with:
`f16_dataset = nonlinear_benchmarks.not_splitted_benchmarks.F16(force_download=True, url="https://data.4tu.nl/file/b6dc643b-ecc6-437c-8a8a-1681650ec3fe/5414dfdc-6e8d-4208-be6e-fa553de9866f")`

I think there's an old hardcoded link in the code, the easy fix is to modify line 145 of non_splitted_benchmarks.py

**Comment by GerbenBeintema** [comment]
Thanks for the notification that the link broke. I updated the link to the F16 dataset downloader.

Commit: https://github.com/GerbenBeintema/nonlinear_benchmarks/commit/0736580fe1e6602346540047cf469bc1df74db14
